// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "amplifytestapp-20190107092959-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://amplifytestapp-20190107092959-hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:5df21e55-378f-4655-abd6-de53278b7754",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_5hFYWWJo7",
    "aws_user_pools_web_client_id": "5dm6lrntq5go0su1nlukebc4ar"
};


export default awsmobile;
